services:
  - type: worker
    name: 10j-class-bot
    runtime: node
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: node bot.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
